
env:

  # Docker / Docker Compose paths
  KEG_DOCKER_FILE: "{{ cli.taps.links.vab }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.links.vab }}/container/values.yml"
  # The default docker-compose file path
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.links.vab }}/container/docker-compose.yml"

  # The KEG_CONTEXT_PATH env should be the location of the tap being run
  # So it should NOT be set inside the .env file
  KEG_CONTEXT_PATH: "{{ cli.taps.links.vab }}"

  # --- DOCKER ENV CONTEXT --- #

  # Default location of the tap in the docker container
  DOC_APP_PATH: /app
  DOC_APP_PORT: 5000

  # --- GENERAL CONTEXT ENVs --- #

  # Image Build information
  IMAGE: va-backend
  VERSION: "0.0.1"
  CONTAINER_NAME: va-backend

